name: linux-x86_64

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - 'examples/**'
      - 'nerves/**'
      - 'Makefile.win'
      - '.github/FUNDING.yml'
      - '.github/workflows/nerves-*'
      - '.github/workflows/macos-*'
      - '.github/workflows/windows-*'
      - '.github/workflows/test-*.yml'
      - '.github/workflows/linux-arm64.yml'
      - '.github/workflows/linux-armv7.yml'
      - '.github/workflows/linux-ppc64le.yml'
      - '.github/workflows/linux-s390x.yml'
      - '.github/workflows/linux-precompile.yml'
  push:
    branches:
      - main
      - feature-*
      - experimental-*
      - test-*
      - fix-*
    paths-ignore:
      - '**/README.md'
      - 'examples/**'
      - 'nerves/**'
      - 'Makefile.win'
      - '.github/FUNDING.yml'
      - '.github/workflows/nerves-*'
      - '.github/workflows/macos-*'
      - '.github/workflows/windows-*'
      - '.github/workflows/test-*.yml'
      - '.github/workflows/linux-arm64.yml'
      - '.github/workflows/linux-armv7.yml'
      - '.github/workflows/linux-ppc64le.yml'
      - '.github/workflows/linux-s390x.yml'
      - '.github/workflows/linux-precompile.yml'
  workflow_dispatch:

jobs:
  mix_test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2
      
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.2
          elixir-version: 1.13.3

      - name: Install system dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential automake autoconf pkg-config bc m4 unzip zip curl git libssl-dev gzip libncurses5-dev erlang-inets erlang-os-mon erlang-runtime-tools erlang-ssl erlang-dev python3 ca-certificates
          sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavresample-dev ffmpeg

      - name: Mix Compile
        run: |
          mix deps.get
          mix compile

      - name: Mix Test
        run: |
          mix test --include require_downloading --include require_ffmpeg
