name: linux-ppc64le

on:
  workflow_dispatch:

jobs:
  mix_test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: ppc64le
            distro: ubuntu20.04

    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          
          shell: /bin/bash
          install: |
            apt-get update -q -y
            apt-get install -y build-essential gnupg2 automake autoconf pkg-config bc m4 unzip zip wget curl git libssl-dev libncurses5-dev python3 ca-certificates
            curl -fSL https://repo.uwucocoa.moe/pgp.key | apt-key add -
            echo "deb [arch=ppc64el] https://repo.uwucocoa.moe/ stable main" | tee /etc/apt/sources.list.d/uwucocoa.list
            apt-get update -q -y
            apt-get install cmake-uwu erlang-uwu
            wget https://github.com/elixir-lang/elixir/releases/download/v1.13.3/Precompiled.zip -O Precompiled.zip
            unzip -o Precompiled.zip
            export PATH="$(pwd)/Precompiled/bin:${PATH}"
            mix local.hex --force
            mix local.rebar --force

          run: |
            export PATH="/usr/local/bin:$(pwd)/Precompiled/bin:${PATH}"
            mix deps.get
            mix compile
