name: OpenCV-Compatibility

on:
  push:
    branches:
      - opencv-compatibility
    paths-ignore:
      - '**/README.md'
      - 'examples/**'
      - 'test/**'
      - 'c_src/**'
      - 'lib/**'
      - 'patches/**'
      - 'nerves/**'
      - '.github/FUNDING.yml'
      - '.github/workflows/nerves-*'
      - '.github/workflows/macos-*'
      - '.github/workflows/linux-*'
      - '.github/workflows/test-python-*'

  workflow_dispatch:

jobs:
  python_compatibility:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        opencv-version: ["4.5.3", "4.5.2", "4.5.1", "4.5.0", "4.4.0", "4.3.0", "4.2.0", "4.1.2", "4.1.1", "4.1.0", "4.0.1", "4.0.0"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "24.1.5"
          elixir-version: "1.13"

      - name: Install system dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential automake autoconf pkg-config bc m4 unzip zip curl git libssl-dev libncurses5-dev ca-certificates
          sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavresample-dev ffmpeg

      - name: Mix Compile
        run: |
          export OPENCV_VER=${{ matrix.opencv-version }}
          mix deps.get
          mix compile

      - name: Mix Test
        run: |
          export OPENCV_VER=${{ matrix.opencv-version }}
          mix test --include dnn
